import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./nav";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className="flex-col bg-slate-950 font-mono rounded-2xl mt-5 mx-2">
        <header className="header">
          <NavBar />
        </header>

        <div className="group mx-2 text-center bg-slate-900 text-white rounded-2xl">{children}</div>
      </body>
    </html>
  );
}
